[build]
  command = "npm install && ionic build --prod"  # Comando para instalar dependencias y construir la app
  publish = "www"  # Carpeta donde Netlify buscará los archivos compilados (especifica la salida de Ionic)
